Repository Seagate/cortx-k8s, pull requests merged in 2022-08, with the labels that each got.

#347 CORTX-33749 - Workaround for conntrack table issues
  .gitignore
  README.md
  doc/prereq-deploy-use-cases.md
  k8_cortx_cloud/prereq-deploy-cortx-cloud.sh
Labels: documentation, cla-signed

#348 CORTX-33135: cortx-setup logging enhancements
  README.md
  charts/cortx/README.md
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/_images.tpl
  charts/cortx/templates/client/statefulset.yaml
  charts/cortx/templates/control/deployment.yaml
  charts/cortx/templates/ha/deployment.yaml
  charts/cortx/templates/server/statefulset.yaml
  charts/cortx/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#349 CORTX-33142 - FS glossary updates
  GLOSSARY.md
Labels: documentation, cla-signed

#350 Bump CORTX version to 886
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  k8_cortx_cloud/solution.example.yaml
Labels: cla-signed

#354 Bump VERSION to v0.11.0_dev
  k8_cortx_cloud/VERSION
Labels: cla-signed

#351 CORTX-32209 - Manual PV use case
  README.md
  doc/advanced-deployment-scenarios.md
  doc/images/advanced-use-cases-manual-pvs-01.png
  doc/images/advanced-use-cases-manual-pvs-02.png
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: documentation, enhancement, cla-signed, k8s

#333 CORTX-33054: Use Consul as Confstore for CORTX components
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/_images.tpl
  charts/cortx/templates/client/statefulset.yaml
  charts/cortx/templates/control/deployment.yaml
  charts/cortx/templates/data/statefulset.yaml
  charts/cortx/templates/ha/deployment.yaml
  charts/cortx/templates/server/statefulset.yaml
  k8_cortx_cloud/logs-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
Labels: cla-signed, Status: Draft

#357 V0.11.0 branch
  README.md
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/_images.tpl
  charts/cortx/templates/client/statefulset.yaml
  charts/cortx/templates/control/deployment.yaml
  charts/cortx/templates/data/statefulset.yaml
  charts/cortx/templates/ha/deployment.yaml
  charts/cortx/templates/server/statefulset.yaml
  doc/advanced-deployment-scenarios.md
  doc/images/advanced-use-cases-manual-pvs-01.png
  doc/images/advanced-use-cases-manual-pvs-02.png
  k8_cortx_cloud/VERSION
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/logs-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
Labels: cla-signed

#359 Bump CORTX version to 920
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  k8_cortx_cloud/solution.example.yaml
Labels: cla-signed

#361 CORTX-32645: New script: get-logs-from-pvc.sh
  k8_cortx_cloud/get-logs-from-pvc.sh
Labels: cla-signed

#363 CORTX-34043: operator prototype glossary updates
  GLOSSARY.md
Labels: cla-signed

#364 Fix spelling
  CONTRIBUTING.md
  GLOSSARY.md
  charts/cortx/templates/_helpers.tpl
  doc/advanced-deployment-scenarios.md
  doc/cortx-aws-k8s-installation.md
  doc/prereq-deploy-use-cases.md
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/logs-cortx-cloud.sh
  test/regression/utils.py
Labels: cla-signed

#365 CORTX-32834 - glossary updates to reflect template change
  GLOSSARY.md
Labels: documentation, cla-signed

#366 CORTX-33283 - glossary updates for Operator FS
  GLOSSARY.md
Labels: documentation, cla-signed

#367 CORTX-33534: Improve logs-cortx-cloud.sh error handling.
  k8_cortx_cloud/logs-cortx-cloud.sh
Labels: cla-signed
