Repository Seagate/cortx-k8s, pull requests merged in 2022-06, with the labels that each got.

#270 CORTX-32041: configure HAX http endpoint correctly
  README.md
  charts/cortx/README.md
  charts/cortx/templates/_config.yaml.tpl
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/hax/service.yaml
  charts/cortx/templates/server/service.yaml
  charts/cortx/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed

#271 Bump CORTX images to build 803
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  k8_cortx_cloud/solution.example.yaml
Labels: cla-signed

#269 Use release namespace for server domain names
  charts/cortx/templates/_cluster.yaml.tpl
Labels: cla-signed

#277 Fix status script for StatefulSet, label updates, etc.
  charts/cortx/README.md
  charts/cortx/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/rgw/service-headless.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/rgw/statefulset.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#278 Use selectors for StatefulSet lookups
  k8_cortx_cloud/start-cortx-cloud.sh
Labels: cla-signed

#280 CORTX-28968: Server Pod scale out & StatefulSet conversion
  README.md
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  charts/cortx/templates/_cluster.yaml.tpl
  charts/cortx/values.yaml
  doc/images/cortx-ref-arch-k8s-28968.jpg
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-local-pvc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/rgw/service-headless.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/rgw/statefulset.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/shutdown-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
  k8_cortx_cloud/start-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#273 Bump VERSION to v0.8.0.dev0
  k8_cortx_cloud/VERSION
Labels: cla-signed

#279 Cortx 30260: Added version compatibility check feature to upgrade script
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#268 CORTX-32010: improve deployment wait and timeout handling
  README.md
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#281 Add PR checklist items for image updates
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#283 Bump CORTX version to 817
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  k8_cortx_cloud/solution.example.yaml
Labels: cla-signed

#282 CORTX-30143: Merge cortx-server Chart into cortx Chart
  charts/cortx/README.md
  charts/cortx/templates/_cluster.yaml.tpl
  charts/cortx/templates/_config.yaml.tpl
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/server/service-headless.yaml
  charts/cortx/templates/server/service.yaml
  charts/cortx/templates/server/statefulset.yaml
  charts/cortx/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/Chart.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/rgw/service-headless.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#286 CORTX-29859: Migrate Data Pods to be managed by a StatefulSet
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  charts/cortx/templates/_cluster.yaml.tpl
  charts/cortx/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data-blk-data/templates/cortx-data-blk-data-pv.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data-blk-data/templates/cortx-data-blk-data-sc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data-blk-data/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-local-pvc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/data/configmap-nodeconfig.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/data/service-headless.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/data/statefulset.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/shutdown-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
  k8_cortx_cloud/start-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: enhancement, cla-signed, k8s

#288 CORTX-30144: Merge cortx-data Chart into cortx Chart
  charts/cortx/README.md
  charts/cortx/templates/_cluster.yaml.tpl
  charts/cortx/templates/_config.yaml.tpl
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/control/deployment.yaml
  charts/cortx/templates/data/node-configmap.yaml
  charts/cortx/templates/data/service-headless.yaml
  charts/cortx/templates/data/statefulset.yaml
  charts/cortx/templates/ha/deployment.yaml
  charts/cortx/templates/hax/service.yaml
  charts/cortx/templates/server/statefulset.yaml
  charts/cortx/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/Chart.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#289 CORTX-29861: Refactor solution.yaml to support multiple data pods per node
  .github/workflows/lint.yaml
  .gitignore
  README.md
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/generate-cvg-yaml.sh
  k8_cortx_cloud/prereq-deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-validation.sh
  k8_cortx_cloud/start-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: documentation, enhancement, cla-signed, k8s, breaking-change

#292 CORTX-32320: Update docs for upgrade to clarify how images are used
  README.md
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#290 CORTX-30147: misc Chart-related cleanup
  charts/cortx/README.md
  charts/cortx/templates/_cluster.yaml.tpl
  charts/cortx/templates/_config.yaml.tpl
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/control/deployment.yaml
  charts/cortx/templates/data/service-headless.yaml
  charts/cortx/templates/data/statefulset.yaml
  charts/cortx/templates/server/statefulset.yaml
  charts/cortx/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#296 CORTX-28584: Add missing common selector labels
  charts/cortx/templates/control/deployment.yaml
  charts/cortx/templates/control/service.yaml
  charts/cortx/templates/ha/deployment.yaml
  charts/cortx/templates/ha/service-headless.yaml
  charts/cortx/templates/hax/service.yaml
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#299 CORTX-30147: Rename Control service
  charts/cortx/templates/control/service.yaml
  charts/cortx/templates/hax/service.yaml
  charts/cortx/templates/server/service.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#298 CORTX-30147: Simplify upgrade by using selector labels
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#300 v0.8 Merge
  README.md
  k8_cortx_cloud/VERSION
  k8_cortx_cloud/logs-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#303 Bump version to v0.9.0.dev
  k8_cortx_cloud/VERSION
Labels: cla-signed

#304 Update GLOSSARY.md
  GLOSSARY.md
Labels: cla-signed

#302 CORTX-29861: Multiple Data Pods per Node
  .alexrc
  GLOSSARY.md
  README.md
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  charts/cortx/templates/_cluster.yaml.tpl
  charts/cortx/templates/_config.yaml.tpl
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/data/service-headless.yaml
  charts/cortx/templates/data/statefulset.yaml
  charts/cortx/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/generate-cvg-yaml.sh
  k8_cortx_cloud/shutdown-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-validation.sh
  k8_cortx_cloud/start-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: enhancement, cla-signed, k8s
