Repository Seagate/cortx-k8s, pull requests merged in 2022-03, with the labels that each got.

#127 Update CODEOWNERS
  CODEOWNERS
Labels: cla-signed

#124 Fixing broken links and improving them
  README.md
Labels: cla-signed

#129 CORTX-29125: update status-cortx-cloud.sh to return exit code 1 on failure
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#132 CORTX-29121: Doc updates for external services changes
  README.md
Labels: cla-signed

#133 CORTX-29121 readme rgw updates
  README.md
  doc/images/cortx-ref-arch-k8s-pre-rgw.jpg
  doc/images/cortx-ref-arch-k8s.jpg
Labels: documentation, cla-signed

#136 CORTX-28870: Adding the allowable list for Alex scan
  .alexrc
Labels: cla-signed

#130 CORTX-29144: Fix shellcheck issues in logs-cortx-cloud.sh
  .github/workflows/lint.yaml
  k8_cortx_cloud/logs-cortx-cloud.sh
Labels: cla-signed

#125 CORTX-28899: Ability to create multiple LoadBalancer IO services
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed

#139 CORTX-28969: Update solution.yaml with latest supported images
  k8_cortx_cloud/solution.yaml
Labels: cla-signed

#137 CORTX-28904:changed rgw external ports to 80 & 443
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
Labels: cla-signed

#126 CORTX-28579: Basic regression tests for cortx-k8s
  test/regression/checker.py
  test/regression/cluster.py
  test/regression/cortx-k8s-tests.md
  test/regression/deploy.py
  test/regression/destroy.py
  test/regression/example_config.yaml
  test/regression/test_deploy.py
  test/regression/testlists/alltests.yaml
  test/regression/testlists/deploy_all.yaml
  test/regression/testlists/deploy_cortx.yaml
  test/regression/testrunner.py
  test/regression/utils.py
Labels: cla-signed

#143 CORTX-29144: Fix shellcheck issues in status-cortx-cloud.sh
  .github/workflows/lint.yaml
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#147 CORTX-27683: Update hax and motr endpoint values
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#154 Update container images to latest released
  k8_cortx_cloud/solution.yaml
Labels: cla-signed

#144 CORTX-27775: Persistent device path support
  README.md
  k8_cortx_cloud/cortx-cloud-3rd-party-pkg/templates/job-symlink-block-devices.yaml.template
  k8_cortx_cloud/prereq-deploy-cortx-cloud.sh
Labels: enhancement, cla-signed

#155 CORTX-28509: Remove secrets mounts from non-init containers
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/templates/cortx-ha-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
Labels: cla-signed

#151 CORTX-29298: wait for all cortx pods to be in ready state after upgrade support
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#152 CORTX-29228: removed sleep infinity from cortx-rgw conatiner
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
Labels: cla-signed

#150 CORTX-29029: support for multiple m0d instances with group_size
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed

#149 CORTX-29275:Update SSL certificate.
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/ssl-cert/s3.seagate.com.pem
Labels: cla-signed

#156 CORTX-29202: Fix shellcheck issues in deploy-cortx-cloud.sh
  .github/workflows/lint.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#119 Add CloudFormation template
  doc/cortx-aws-k8s-installation.md
  k8_cortx_cloud/templates/cloudformation/3node.json
  k8_cortx_cloud/templates/cloudformation/cloudformation.py
Labels: cla-signed

#161 CORTX-29234: Default nodePorts to `null` in solution.yaml
  README.md
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
Labels: cla-signed

#165 CORTX-27775: Update prereq regtest with interface change
  test/regression/cluster.py
Labels: cla-signed

#157 CORTX-29430: Ports allocated to each ios container are not in an incr…
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#162 Test Cortx k8s single node setup with minikube.
  doc/cortx-minikube-k8s-installation.md
Labels: cla-signed

#160 CORTX-29202: Fix shellcheck issues in shutdown-cortx-cloud.sh
  .github/workflows/lint.yaml
  k8_cortx_cloud/shutdown-cortx-cloud.sh
Labels: bug, cla-signed

#167 CORTX:29228:removed sleep infinity from csm & hax
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
Labels: cla-signed

#158 CORTX-29137: Support setting of some arbitrary config.yaml values
  README.md
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
Labels: enhancement, cla-signed

#169 CORTX-29503 - removed sleep infinity from rgw,csm & hax
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
Labels: cla-signed

#174 CORTX-29541: Remove remaining references to openldap from README.md
  README.md
Labels: cla-signed

#171 CORTX-27777 - Prereq script documentation updates
  README.md
  doc/prereq-deploy-use-cases.md
  k8_cortx_cloud/solution-documentation.md
Labels: documentation, cla-signed

#172 CORTX-29179: Update RGW endpoints
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-hax-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
Labels: cla-signed

#170 CORTX-29122: Updated use of CORTX Secrets
  README.md
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed

#175 CORTX-29179: Remove common.s3.num_inst from solution.yaml validation
  .github/workflows/lint.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed

#176 CORTX-29122: Restore CORTX passwords
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
Labels: cla-signed

#177 CORTX-29548: Support rgw image in upgrade-cortx-cloud.sh
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#168 CORTX-28534: Granular deployment (Data-pod-only)
  README.md
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_cluster.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/shutdown-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
  k8_cortx_cloud/start-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#178 Lint solution.example.yaml
  .github/workflows/lint.yaml
Labels: cla-signed

#179 CORTX-29672: Remove unused s3 server settings
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-networkpolicy.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed

#185 CORTX-29634: Update Consul image version to 1.11.4
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
Labels: cla-signed

#186 CORTX-29800: Add newline to final printf of deploy-cortx-cloud.sh
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#190 Merge v0.2 branch into main
  k8_cortx_cloud/VERSION
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
Labels: cla-signed

#182 CORTX-29590: Seamless rolling upgrade framework to address temporary …
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#184 CORTX-29435: Add GitHub Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement, cla-signed

#193 CORTX-29809: Upgrade script should throw an error when invalid image passed.
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed
