Repository Seagate/cortx-k8s, pull requests merged in 2022-09, with the labels that each got.

#368 CORTX-31017: Add check for cortx already deployed
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#370 V0.12.0 branch
  CONTRIBUTING.md
  GLOSSARY.md
  README.md
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  charts/cortx/ssl-cert/cortx.pem
  charts/cortx/templates/_config.yaml.tpl
  charts/cortx/templates/_helpers.tpl
  charts/cortx/templates/client/statefulset.yaml
  charts/cortx/templates/control/deployment.yaml
  charts/cortx/templates/data/statefulset.yaml
  charts/cortx/templates/ha/deployment.yaml
  charts/cortx/templates/server/statefulset.yaml
  charts/cortx/templates/tls-configmap.yaml
  charts/cortx/templates/tls-secret.yaml
  charts/cortx/values.yaml
  doc/advanced-deployment-scenarios.md
  doc/cortx-aws-k8s-installation.md
  doc/prereq-deploy-use-cases.md
  k8_cortx_cloud/VERSION
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/get-logs-from-pvc.sh
  k8_cortx_cloud/logs-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  test/regression/utils.py
Labels: cla-signed

#371 Bump VERSION to v0.13.0_dev
  k8_cortx_cloud/VERSION
Labels: cla-signed

#374 CORTX-34141: Add -d option to get-logs-from-pvc.sh
  k8_cortx_cloud/get-logs-from-pvc.sh
Labels: cla-signed

#373 CORTX-34174: Improve options to logs-cortx-cloud.sh
  k8_cortx_cloud/logs-cortx-cloud.sh
Labels: cla-signed

#377 CORTX-34189 Fix status-cortx-cloud.sh regression (data-only deploy)
  k8_cortx_cloud/status-cortx-cloud.sh
  test/regression/data-only.yaml
  test/regression/test_deploy.py
  test/regression/testlists/alltests.yaml
  test/regression/testlists/deploy_all.yaml
Labels: cla-signed

#378 Updated GLOSSARY page with redirect to seagate/cortx
  GLOSSARY.md
Labels: documentation, cla-signed

#379 CORTX-34139: Remove all deprecated code
  charts/cortx/templates/control/service.yaml
  charts/cortx/templates/server/service.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#329 Let Helm manage dependent Chart install
  charts/cortx/README.md
  charts/cortx/README.md.gotmpl
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed, Status: Draft

#381 Bump CORTX version to 950
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  k8_cortx_cloud/solution.example.yaml
Labels: cla-signed

#380 CORTX-34284: Do not count cortx-consul-client pods in status check
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#384 V0.13.0 merge
  GLOSSARY.md
  charts/cortx/Chart.yaml
  charts/cortx/README.md
  charts/cortx/README.md.gotmpl
  charts/cortx/templates/control/service.yaml
  charts/cortx/templates/server/service.yaml
  k8_cortx_cloud/VERSION
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/get-logs-from-pvc.sh
  k8_cortx_cloud/logs-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/status-cortx-cloud.sh
  test/regression/data-only.yaml
  test/regression/test_deploy.py
  test/regression/testlists/alltests.yaml
  test/regression/testlists/deploy_all.yaml
Labels: cla-signed

#385 CORTX-32850: Add Server container probes
  charts/cortx/README.md
  charts/cortx/templates/server/statefulset.yaml
  charts/cortx/values.yaml
Labels: cla-signed
