Repository Seagate/cortx-k8s, pull requests merged in 2022-02, with the labels that each got.

#58 EOS-27541: Add Github Action for shellcheck
  .github/workflows/lint.yaml
  .shellcheckrc
Labels: cla-signed

#72 v0.0.21
  k8_cortx_cloud/VERSION
  k8_cortx_cloud/solution.yaml
Labels: cla-signed

#74 Patch for README.md GitHub formatting
  README.md
Labels: documentation, cla-signed

#76 Update .gitignore file
  .gitignore
Labels: cla-signed

#70 Remove unneeded control services
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#78 Merge main into Integration
  doc/cortx-aws-k8s-installation.md
Labels: cla-signed

#80 EOS-27546: Silence 'Defaulting container name' log collection messages
  k8_cortx_cloud/logs-cortx-cloud.sh
Labels: cla-signed

#90 EOS-28535: Remove for loop in function deployCortxSecrets()
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#91 EOS-28022: Support default IAM configuration fields
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
Labels: cla-signed

#88 EOS-27644 Test and qualify granular deployment-Data Pod only
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/cluster-data-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-data-template.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#92 EOS-28544: Remove check from status for control-headless / -clusterip svcs
  k8_cortx_cloud/status-cortx-cloud.sh
Labels: cla-signed

#93 EOS-28489 remove dup line in cortxha helm deploy
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#94 EOS-27425: Distruptive container image upgrades
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#96 Initial version of CONTRIBUTING.md et al
  CODEOWNERS
  CONTRIBUTING.md
  MAINTAINERS.md
Labels: documentation, cla-signed

#100 EOS-27447 - clusterip svc for hax
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-hax-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: enhancement

#106 CORTX-27406: Manage CORTX ConfigMap via Helm
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/.helmignore
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/Chart.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/other/secret-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_cluster.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_helpers.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/cluster-node-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/cluster-storage-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/cluster-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/configmap.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/tls-configmap.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
Labels: cla-signed

#111 Remove Mocking from Control pod and Server pod
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
Labels: cla-signed

#114 CORTX-28890: removed hardcoded rgw inst from config template
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/config-template.yaml
Labels: cla-signed

#115 CORTX- 28078 - RGW integration, phase 1
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_cluster.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: enhancement, cla-signed, k8s

#120 CORTX-27406: Allow customization of external service ports
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed

#109 Updates to AWS Kubernetes QSG
  doc/cortx-aws-k8s-installation.md
Labels: cla-signed

#122 CORTX-29102 - Fix AWS QSG URL typo
  README.md
Labels: bug, documentation, cla-signed
