Repository Seagate/cortx-k8s, pull requests merged in 2022-04, with the labels that each got.

#194 CORTX-29435: Fix contact links (issue forms)
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#196 CORTX-29537: Fix shellcheck issues in destroy-cortx-cloud.sh
  .github/workflows/lint.yaml
  k8_cortx_cloud/destroy-cortx-cloud.sh
Labels: cla-signed

#198 CORTX-30138 - added InitContainer debug troubleshooting steps
  README.md
Labels: documentation, cla-signed

#197 CORTX-29986: remove PID File at the end of the script to avoid parall…
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#199 CORTX-29698: Update regtests for v0.2.0 solution.yaml updates
  test/regression/cluster.py
  test/regression/cortx-k8s-tests.md
  test/regression/example_config.yaml
  test/regression/testlists/alltests.yaml
Labels: cla-signed

#183 CORTX-29720 Remove deprecated keys from config files - Service framework
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
  k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
Labels: cla-signed, deprecation, deprecation-needs-acknowledgement

#203 Bump CORTX images to build 713
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution.yaml
Labels: cla-signed

#204 CORTX-29537: Fix shellcheck issues in generate-cvg-yaml.sh
  .github/workflows/lint.yaml
  k8_cortx_cloud/generate-cvg-yaml.sh
Labels: cla-signed

#191 CORTX-29822: Remove items deprecated in v0.2.0
  .github/workflows/lint.yaml
  k8_cortx_cloud/logs-cortx-cloud.sh
  k8_cortx_cloud/solution.example.yaml
  k8_cortx_cloud/solution.yaml
  k8_cortx_cloud/solution_stub.yaml
Labels: cla-signed, breaking-change, deprecation-needs-acknowledgement

#208 Relocate Helm repo install to pre-req function
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#207 CORTX-29537: Update shellcheck ignored files
  .github/workflows/lint.yaml
Labels: cla-signed

#205 CORTX-29592: Support deploy into non-default namespace
  README.md
  k8_cortx_cloud/cortx-cloud-3rd-party-pkg/templates/local-path-storage-template.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-local-pvc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/templates/cortx-control-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-control/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data-blk-data/templates/cortx-data-blk-data-pv.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data-blk-data/templates/cortx-data-blk-data-sc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data-blk-data/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-local-pvc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/templates/cortx-data-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-data/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/templates/cortx-ha-local-pvc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/templates/cortx-ha-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/templates/cortx-ha-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-ha/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-hax-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-namespace.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-networkpolicy.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-role.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-rolebinding.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-serviceaccount.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/values.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-local-pvc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/values.yaml
  k8_cortx_cloud/deploy-cortx-cloud.sh
  k8_cortx_cloud/destroy-cortx-cloud.sh
  test/regression/cluster.py
Labels: cla-signed

#210 CORTX-29537: Fix shellcheck issues in prereq-deploy-cortx-cloud.sh
  .github/workflows/lint.yaml
  k8_cortx_cloud/prereq-deploy-cortx-cloud.sh
Labels: cla-signed

#209 CORTX-30780: Update status and logs scripts with proper namespace
  k8_cortx_cloud/logs-cortx-cloud.sh
  k8_cortx_cloud/status-cortx-cloud.sh
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#213 CORTX-30708: Fix shellcheck issues in parse scripts
  .github/workflows/lint.yaml
  k8_cortx_cloud/parse_scripts/parse_yaml.sh
  k8_cortx_cloud/parse_scripts/subst.sh
  k8_cortx_cloud/parse_scripts/yaml_extract_block.sh
  k8_cortx_cloud/parse_scripts/yaml_insert_block.sh
  k8_cortx_cloud/parse_scripts/yaml_update_block.sh
Labels: cla-signed

#214 CORTX-30781 Add regression test for default vs other namespace
  test/regression/cluster.py
  test/regression/test_deploy.py
  test/regression/testlists/alltests.yaml
  test/regression/testlists/deploy_all.yaml
Labels: cla-signed

#181 CORTX-29723: remove mocking from cortx-client-pod init container
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
Labels: cla-signed

#211 CORTX-29807 Update README.md with granular data-only deployment
  README.md
Labels: cla-signed

#216 CORTX-30943: Support specified namespace for cortx-client pods
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-local-pvc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-pod.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/templates/cortx-client-svc.yaml
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-client/values.yaml
Labels: cla-signed

#200 CORTX-29869: Add rgw_s3 service for RGW component in cluster config file
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_cluster.tpl
  k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-configmap/templates/_config.tpl
Labels: cla-signed

#218 CORTX-30971: Pin helm chart release versions
  k8_cortx_cloud/deploy-cortx-cloud.sh
Labels: cla-signed

#221 CORTX-30215: Remove hare bug workaround from upgrade-cortx-cloud.sh script
  k8_cortx_cloud/upgrade-cortx-cloud.sh
Labels: cla-signed

#226 CORTX-30015: Specify python3 bin with "/usr/bin/env python3"
  test/regression/deploy.py
  test/regression/destroy.py
  test/regression/test_deploy.py
  test/regression/testrunner.py
Labels: cla-signed
